# -*- encoding: utf-8 -*-
require File.expand_path('../lib/csv_to_object/version', __FILE__)

Gem::Specification.new do |gem|
  gem.authors       = ["Ian Whitney", "Davin Lagerroos"]
  gem.email         = ["iwhitney@ssa-i.org", "dlagerroos@ssa-i.org"]
  gem.description   = %q{Takes a CSV file and returns a a collection of objects generated by that CSV file.}
  gem.summary       = %q{Given the path to a CSV file, will return a collection of objects. The csv file name must match the name of an object the gem can instantiate. The first line of the csv file must define attribute names. The following lines contain the data that will be assigned to those attributes.}
  gem.homepage      = "https://github.com/SeniorServiceAmerica/csv_to_object"

  gem.files         = `git ls-files`.split($\)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.name          = "csv_to_object"
  gem.require_paths = ["lib"]
  gem.version       = CsvToObject::VERSION
  
  gem.add_development_dependency "rspec"
end
